In [1]:
import pandas as pd
import numpy as np

In [2]:
path = 'C:/Users/Uriel/Documents/DELFIN/Casas de Seguridad/thogar_envipe2013/thogar.csv'
df = pd.read_csv(path, encoding='latin', low_memory=False)

In [13]:
df

,CONTROL,VIV_SEL,HOGAR,RESUL_H,N_INF,R_SEL,TOT_PER,FAC_HOG,DOM,EST,UPM
0,10002,1,1,B,1,1,1,238,U,6,1
1,10002,2,1,B,1,1,4,238,U,6,1
2,10002,4,1,B,1,1,3,238,U,6,1
3,10002,5,1,B,1,1,1,238,U,6,1
4,10004,1,1,B,1,2,4,179,U,6,2
5,10004,2,1,B,2,3,6,179,U,6,2
6,10004,3,1,B,1,2,4,179,U,6,2
7,10004,4,1,B,1,1,5,179,U,6,2
8,10004,5,1,B,2,1,5,179,U,6,2
9,10005,1,1,A,3,2,6,175,U,6,3
10,10005,2,1,B,1,2,3,175,U,6,3
11,10005,3,1,B,1,1,1,175,U,6,3
12,10005,4,1,A,2,1,3,175,U,6,3
13,10005,5,1,A,2,1,2,175,U,6,3
14,10006,1,1,B,4,6,7,152,U,6,4
15,10006,2,1,B,1,1,4,152,U,6,4
16,10006,3,1,B,8,4,13,152,U,6,4
17,10006,4,1,A,1,1,2,152,U,6,4
18,10006,5,1,B,1,1,3,152,U,6,4
19,10007,1,1,B,2,1,2,236,U,5,5
20,10007,2,1,B,1,2,2,236,U,5,5
21,10007,3,1,B,3,3,5,236,U,5,5
22,10007,4,1,A,1,2,4,236,U,5,5
23,10007,5,1,B,1,1,1,236,U,5,5
24,10011,1,1,A,2,2,5,209,U,5,6
25,10011,2,1,A,1,1,1,209,U,5,6
26,10011,3,1,B,1,1,2,209,U,5,6
27,10011,4,1,A,2,1,5,209,U,5,6
28,10011,5,1,A,1,1,3,209,U,5,6
29,10012,1,1,B,1,2,2,180,U,7,7
...,...,...,...,...,...,...,...,...,...,...,...
84719,327008,12,1,B,2,4,6,161,R,265,13315
84720,327008,13,1,B,2,1,2,161,R,265,13315
84721,327008,14,1,B,1,1,1,161,R,265,13315
84722,327008,16,1,A,2,2,2,161,R,265,13315
84723,327008,18,1,B,2,1,2,161,R,265,13315
84724,327008,19,1,B,3,1,3,161,R,265,13315
84725,327008,20,1,B,1,2,6,161,R,265,13315
84726,327008,21,1,B,1,1,3,161,R,265,13315
84727,327008,22,1,B,2,3,3,161,R,265,13315
84728,327008,23,1,B,1,1,2,161,R,265,13315
84729,327009,1,1,B,2,1,4,225,R,265,13316
84730,327009,2,1,B,1,1,2,225,R,265,13316
84731,327009,3,1,B,2,1,5,225,R,265,13316
84732,327009,4,1,B,2,2,4,225,R,265,13316
84733,327009,5,1,A,2,1,5,225,R,265,13316
84734,327009,7,1,A,1,2,5,225,R,265,13316
84735,327009,8,1,B,2,2,4,225,R,265,13316
84736,327009,9,1,B,1,1,4,225,R,265,13316
84737,327009,10,1,B,2,2,5,225,R,265,13316
84738,327009,11,1,B,1,1,6,225,R,265,13316
84739,327009,12,1,A,1,1,3,225,R,265,13316
84740,327009,12,2,B,2,2,2,225,R,265,13316
84741,327009,13,1,A,1,1,5,225,R,265,13316
84742,327009,14,1,B,2,1,4,225,R,265,13316
84743,327009,15,1,A,2,2,4,225,R,265,13316
84744,327009,16,1,B,1,2,2,225,R,265,13316
84745,327009,17,1,B,1,1,6,225,R,265,13316
84746,327009,18,1,B,2,1,5,225,R,265,13316
84747,327009,19,1,B,1,2,4,225,R,265,13316
84748,327009,21,1,B,2,1,3,225,R,265,13316

El primer paso, sera ver si las columnas contienen valores nulos. Lo cual se realizara de la siguiente forma

In [18]:
df.UPM.isnull().value_counts()

False    84749
Name: UPM, dtype: int64

En caso de que alguna columna tenga valores nulos, se remplazan de la siguiente forma

In [11]:
df['R_SEL'].fillna('1', inplace = True)

Se puede ver que la tabla no esta muy sucia, por lo que solo le haremos los cambios necesarios

Se modificaran las columnas 'RESUL_H' y 'DOM' debido a que sus valores son categoricos, por lo que se remplazaran por numeros.

Columna RESUL_H; Valores originales : A, B, C, D, E Valores nuevos : 1, 2, 3, 4, 5

Columna DOMINIO; Valores originales : U, C, R Valores nuevos : 1, 2, 3

Remplaso de valores de la columna RESUL_H

In [20]:
df.RESUL_H=  df.RESUL_H.replace( 'A', "1", regex = True  )

df.RESUL_H=  df.RESUL_H.replace( 'B', "2", regex = True  )

df.RESUL_H=  df.RESUL_H.replace( 'C', "3", regex = True  )

df.RESUL_H=  df.RESUL_H.replace( 'D', "4", regex = True  )

df.RESUL_H=  df.RESUL_H.replace( 'E', "5", regex = True  )

Remplaso de valores de la columna DOMINIO

In [21]:
df.DOM=  df.DOM.replace( 'U', "1", regex = True  )

df.DOM=  df.DOM.replace( 'C', "2", regex = True  )

df.DOM=  df.DOM.replace( 'R', "3", regex = True  )

In [22]:
df

,CONTROL,VIV_SEL,HOGAR,RESUL_H,N_INF,R_SEL,TOT_PER,FAC_HOG,DOM,EST,UPM
0,10002,1,1,2,1,1,1,238,1,6,1
1,10002,2,1,2,1,1,4,238,1,6,1
2,10002,4,1,2,1,1,3,238,1,6,1
3,10002,5,1,2,1,1,1,238,1,6,1
4,10004,1,1,2,1,2,4,179,1,6,2
5,10004,2,1,2,2,3,6,179,1,6,2
6,10004,3,1,2,1,2,4,179,1,6,2
7,10004,4,1,2,1,1,5,179,1,6,2
8,10004,5,1,2,2,1,5,179,1,6,2
9,10005,1,1,1,3,2,6,175,1,6,3
10,10005,2,1,2,1,2,3,175,1,6,3
11,10005,3,1,2,1,1,1,175,1,6,3
12,10005,4,1,1,2,1,3,175,1,6,3
13,10005,5,1,1,2,1,2,175,1,6,3
14,10006,1,1,2,4,6,7,152,1,6,4
15,10006,2,1,2,1,1,4,152,1,6,4
16,10006,3,1,2,8,4,13,152,1,6,4
17,10006,4,1,1,1,1,2,152,1,6,4
18,10006,5,1,2,1,1,3,152,1,6,4
19,10007,1,1,2,2,1,2,236,1,5,5
20,10007,2,1,2,1,2,2,236,1,5,5
21,10007,3,1,2,3,3,5,236,1,5,5
22,10007,4,1,1,1,2,4,236,1,5,5
23,10007,5,1,2,1,1,1,236,1,5,5
24,10011,1,1,1,2,2,5,209,1,5,6
25,10011,2,1,1,1,1,1,209,1,5,6
26,10011,3,1,2,1,1,2,209,1,5,6
27,10011,4,1,1,2,1,5,209,1,5,6
28,10011,5,1,1,1,1,3,209,1,5,6
29,10012,1,1,2,1,2,2,180,1,7,7
...,...,...,...,...,...,...,...,...,...,...,...
84719,327008,12,1,2,2,4,6,161,3,265,13315
84720,327008,13,1,2,2,1,2,161,3,265,13315
84721,327008,14,1,2,1,1,1,161,3,265,13315
84722,327008,16,1,1,2,2,2,161,3,265,13315
84723,327008,18,1,2,2,1,2,161,3,265,13315
84724,327008,19,1,2,3,1,3,161,3,265,13315
84725,327008,20,1,2,1,2,6,161,3,265,13315
84726,327008,21,1,2,1,1,3,161,3,265,13315
84727,327008,22,1,2,2,3,3,161,3,265,13315
84728,327008,23,1,2,1,1,2,161,3,265,13315
84729,327009,1,1,2,2,1,4,225,3,265,13316
84730,327009,2,1,2,1,1,2,225,3,265,13316
84731,327009,3,1,2,2,1,5,225,3,265,13316
84732,327009,4,1,2,2,2,4,225,3,265,13316
84733,327009,5,1,1,2,1,5,225,3,265,13316
84734,327009,7,1,1,1,2,5,225,3,265,13316
84735,327009,8,1,2,2,2,4,225,3,265,13316
84736,327009,9,1,2,1,1,4,225,3,265,13316
84737,327009,10,1,2,2,2,5,225,3,265,13316
84738,327009,11,1,2,1,1,6,225,3,265,13316
84739,327009,12,1,1,1,1,3,225,3,265,13316
84740,327009,12,2,2,2,2,2,225,3,265,13316
84741,327009,13,1,1,1,1,5,225,3,265,13316
84742,327009,14,1,2,2,1,4,225,3,265,13316
84743,327009,15,1,1,2,2,4,225,3,265,13316
84744,327009,16,1,2,1,2,2,225,3,265,13316
84745,327009,17,1,2,1,1,6,225,3,265,13316
84746,327009,18,1,2,2,1,5,225,3,265,13316
84747,327009,19,1,2,1,2,4,225,3,265,13316
84748,327009,21,1,2,2,1,3,225,3,265,13316

Una vez limpia la tabla, se exportara a .csv

In [23]:
df.to_csv('C:/Users/Uriel/Documents/DELFIN/Casas de Seguridad/thogar_envipe2013/thogar_clean2013.csv')